apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-api-deployment
  namespace: fraud-detection
  labels:
    app: fraud-api
spec:
  replicas: 1
  progressDeadlineSeconds: 900
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: fraud-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: fraud-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: fraud-api
          image: partthwadwa/fraud-detection-api:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "250m"
              memory: "768Mi"
            limits:
              cpu: "1500m"
              memory: "3Gi"

          startupProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 20

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5