apiVersion: v1
kind: Service
metadata:
  name: fraud-api-service
  namespace: fraud-detection
  labels:
    app: fraud-api
spec:
  selector:
    app: fraud-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP