apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-streamlit-deployment
  namespace: fraud-detection
  labels:
    app: fraud-streamlit-ui
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: fraud-streamlit-ui
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: fraud-streamlit-ui
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: fraud-streamlit-ui
          image: partthwadwa/fraud-streamlit-ui:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8501

          env:
            - name: FASTAPI_URL
              value: "http://fraud-api-service"
            - name: PUBLIC_API_URL
              value: "http://localhost:8000"

          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"

          startupProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 20

          readinessProbe:
            httpGet:
              path: /
              port: 8501
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /
              port: 8501
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5